// Auto-generated by `rake web:generate`. Do not edit manually.
export const GENERATED_RUNNER_PRESETS = Object.freeze({
  "cpu": {
    "id": "cpu",
    "label": "CPU (examples/8bit/hdl/cpu)",
    "simIrPath": "./assets/fixtures/cpu/ir/cpu_lib_hdl.json",
    "explorerIrPath": "./assets/fixtures/cpu/ir/cpu_hier.json",
    "sourceBundlePath": "./assets/fixtures/cpu/ir/cpu_sources.json",
    "schematicPath": "./assets/fixtures/cpu/ir/cpu_schematic.json",
    "preferredTab": "ioTab",
    "preferredBackend": "compiler",
    "compilerWasmPath": "./assets/pkg/ir_compiler_cpu.wasm",
    "enableApple2Ui": false,
    "usesManualIr": false,
    "defaultBin": {
      "path": "./assets/fixtures/cpu/software/conway_glider_80x24.bin",
      "offset": 0,
      "space": "main",
      "startPc": 32,
      "resetAfterLoad": true
    },
    "timing": {
      "cyclesPerHertz": 1,
      "hertzLabel": "CPU"
    },
    "io": {
      "enabled": true,
      "api": "generic",
      "memory": {
        "dumpStart": 0,
        "dumpLength": 65536,
        "addressSpace": 65536,
        "viewMapped": true,
        "dumpReadMapped": true,
        "directWriteMapped": true
      },
      "display": {
        "enabled": true,
        "mode": "cpu8bit_text",
        "text": {
          "start": 2048,
          "width": 80,
          "height": 24,
          "rowStride": 80,
          "rowLayout": "linear",
          "charMask": 255,
          "asciiMin": 32,
          "asciiMax": 126
        }
      },
      "keyboard": {
        "enabled": true,
        "mode": "memory_mapped",
        "dataAddr": 254,
        "strobeAddr": 255,
        "strobeValue": 1,
        "strobeClearValue": 0,
        "upperCase": true,
        "setHighBit": false,
        "enterCode": 13,
        "backspaceCode": 8
      },
      "pcSignalCandidates": [
        "pc_out"
      ],
      "watchSignals": [
        "pc_out",
        "acc_out",
        "sp_out",
        "state_out",
        "zero_flag_out",
        "mem_addr",
        "mem_read_en",
        "mem_write_en",
        "halted"
      ]
    },
    "defaults": {
      "stepTicks": 100,
      "runBatch": 2000,
      "uiUpdateCycles": 2000
    }
  },
  "mos6502": {
    "id": "mos6502",
    "label": "MOS 6502 CPU Runner",
    "simIrPath": "./assets/fixtures/mos6502/ir/mos6502.json",
    "explorerIrPath": "./assets/fixtures/mos6502/ir/mos6502_hier.json",
    "sourceBundlePath": "./assets/fixtures/mos6502/ir/mos6502_sources.json",
    "schematicPath": "./assets/fixtures/mos6502/ir/mos6502_schematic.json",
    "compilerWasmPath": "./assets/pkg/ir_compiler_mos6502.wasm",
    "preferredTab": "ioTab",
    "enableApple2Ui": false,
    "usesManualIr": false,
    "defaultBin": {
      "path": "./assets/fixtures/mos6502/memory/karateka_mem.rhdlsnap",
      "offset": 0,
      "space": "main",
      "resetAfterLoad": true
    },
    "timing": {
      "cyclesPerHertz": 1,
      "hertzLabel": "6502"
    },
    "io": {
      "enabled": true,
      "api": "generic",
      "memory": {
        "dumpStart": 0,
        "dumpLength": 65536,
        "addressSpace": 65536,
        "viewMapped": true,
        "dumpReadMapped": true,
        "directWriteMapped": true
      },
      "display": {
        "enabled": true,
        "mode": "apple2",
        "text": {
          "start": 1024,
          "width": 40,
          "height": 24,
          "rowStride": 128,
          "rowLayout": "apple2",
          "charMask": 127,
          "asciiMin": 32,
          "asciiMax": 126
        }
      },
      "keyboard": {
        "enabled": true,
        "mode": "apple2"
      },
      "watchSignals": [
        "pc_debug",
        "opcode_debug",
        "a_debug",
        "x_debug",
        "y_debug",
        "s_debug",
        "p_debug",
        "speaker"
      ]
    }
  },
  "apple2": {
    "id": "apple2",
    "label": "Apple II System Runner",
    "simIrPath": "./assets/fixtures/apple2/ir/apple2.json",
    "explorerIrPath": "./assets/fixtures/apple2/ir/apple2_hier.json",
    "sourceBundlePath": "./assets/fixtures/apple2/ir/apple2_sources.json",
    "schematicPath": "./assets/fixtures/apple2/ir/apple2_schematic.json",
    "romPath": "./assets/fixtures/apple2/memory/appleiigo.rom",
    "preferredTab": "ioTab",
    "enableApple2Ui": true,
    "usesManualIr": false,
    "autoLoadOnBoot": true,
    "defaultBin": {
      "path": "./assets/fixtures/apple2/memory/karateka_mem.bin",
      "offset": 0,
      "space": "main",
      "startPc": "0xB82A",
      "resetAfterLoad": true
    },
    "timing": {
      "cyclesPerHertz": 1,
      "hertzLabel": "6502"
    },
    "io": {
      "enabled": true,
      "api": "apple2",
      "memory": {
        "dumpStart": 0,
        "dumpLength": 49152,
        "addressSpace": 65536,
        "viewMapped": true,
        "dumpReadMapped": false,
        "directWriteMapped": false
      },
      "display": {
        "enabled": true,
        "mode": "apple2"
      },
      "keyboard": {
        "enabled": true,
        "mode": "apple2_special"
      },
      "sound": {
        "enabled": true,
        "mode": "apple2_special"
      }
    },
    "defaults": {
      "displayHires": true,
      "displayColor": true,
      "memoryFollowPc": true
    }
  },
  "gameboy": {
    "id": "gameboy",
    "label": "Game Boy System Runner",
    "simIrPath": "./assets/fixtures/gameboy/ir/gameboy.json",
    "explorerIrPath": "./assets/fixtures/gameboy/ir/gameboy_hier.json",
    "sourceBundlePath": "./assets/fixtures/gameboy/ir/gameboy_sources.json",
    "schematicPath": "./assets/fixtures/gameboy/ir/gameboy_schematic.json",
    "preferredTab": "ioTab",
    "enableApple2Ui": false,
    "usesManualIr": false,
    "defaultBin": {
      "path": "./assets/fixtures/gameboy/roms/dmg_boot.bin",
      "offset": 0,
      "space": "boot_rom",
      "resetAfterLoad": true
    },
    "timing": {
      "cyclesPerHertz": 1,
      "hertzLabel": "SM83"
    }
  }
});
export const GENERATED_RUNNER_ORDER = Object.freeze(["cpu","mos6502","apple2","gameboy"]);
export const GENERATED_DEFAULT_RUNNER_ID = "apple2";
