FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  bash \
  bc \
  binutils-riscv64-linux-gnu \
  bison \
  build-essential \
  ca-certificates \
  clang \
  cpio \
  file \
  flex \
  gawk \
  gcc-riscv64-linux-gnu \
  git \
  make \
  patch \
  perl \
  python3 \
  rsync \
  sed \
  tar \
  unzip \
  wget \
  xz-utils \
  && rm -rf /var/lib/apt/lists/*
