# frozen_string_literal: true

require 'spec_helper'

require_relative '../../../../examples/sparc64/utilities/integration/staged_verilog_bundle'

RSpec.describe RHDL::Examples::SPARC64::Integration::StagedVerilogBundle do
  let(:cache_root) { Dir.mktmpdir('sparc64_staged_verilog_bundle_spec') }

  after do
    FileUtils.rm_rf(cache_root)
  end

  it 'stages the SPARC64 s1_top mixed-source bundle with importer-managed fast-boot patching', timeout: 120 do
    result = described_class.new(cache_root: cache_root, fast_boot: true).build

    expect(result.top_module).to eq('s1_top')
    expect(File).to exist(result.top_file)
    expect(result.source_files).not_to be_empty
    expect(result.verilator_args).to include('-DFPGA_SYN')
    expect(described_class::FAST_BOOT_PATCHES_DIR).to be_a(String)
    expect(Dir.glob(File.join(described_class::FAST_BOOT_PATCHES_DIR, '*.patch'))).not_to be_empty

    os2wb_file = File.join(result.build_dir, 'patched_reference', 'os2wb', 'os2wb.v')
    os2wb_dual_file = File.join(result.staged_root, 'os2wb', 'os2wb_dual.v')
    ifu_file = File.join(result.staged_root, 'T1-CPU', 'ifu', 'sparc_ifu.v')
    ifu_fcl_file = File.join(result.staged_root, 'T1-CPU', 'ifu', 'sparc_ifu_fcl.v')
    ifu_fdp_file = File.join(result.staged_root, 'T1-CPU', 'ifu', 'sparc_ifu_fdp.v')
    ifu_swl_file = File.join(result.staged_root, 'T1-CPU', 'ifu', 'sparc_ifu_swl.v')
    exu_rml_file = File.join(result.staged_root, 'T1-CPU', 'exu', 'sparc_exu_rml.v')
    irf_register_file = File.join(result.build_dir, 'patched_reference', 'T1-common', 'srams', 'bw_r_irf_register.v')
    staged_irf_register_file = File.join(result.staged_root, 'T1-common', 'srams', 'bw_r_irf_register.v')
    lsu_file = File.join(result.staged_root, 'T1-CPU', 'lsu', 'lsu.v')
    lsu_qctl1_file = File.join(result.staged_root, 'T1-CPU', 'lsu', 'lsu_qctl1.v')
    lsu_qctl2_file = File.join(result.staged_root, 'T1-CPU', 'lsu', 'lsu_qctl2.v')
    sparc_rtl_file = File.join(result.staged_root, 'T1-CPU', 'rtl', 'sparc.v')
    tlu_tcl_file = File.join(result.staged_root, 'T1-CPU', 'tlu', 'tlu_tcl.v')
    support_stubs_file = File.join(result.staged_root, '__rhdl_sparc64_hierarchy_stubs.v')

    expect(File).to exist(os2wb_file)
    expect(File).to exist(os2wb_dual_file)
    expect(File).to exist(ifu_file)
    expect(File).to exist(ifu_fcl_file)
    expect(File).to exist(ifu_fdp_file)
    expect(File).to exist(ifu_swl_file)
    expect(File).to exist(exu_rml_file)
    expect(File).to exist(irf_register_file)
    expect(File).to exist(staged_irf_register_file)
    expect(File).to exist(lsu_file)
    expect(File).to exist(lsu_qctl1_file)
    expect(File).to exist(lsu_qctl2_file)
    expect(File).to exist(sparc_rtl_file)
    expect(File).to exist(tlu_tcl_file)
    expect(File).to exist(support_stubs_file)

    staged_irf_register_source = File.read(staged_irf_register_file)
    expect(staged_irf_register_source).to include('reg	[71:0]	reg_th0 /* verilator public_flat_rw */;')
    expect(staged_irf_register_source).to include('reg	[71:0]	reg_th3 /* verilator public_flat_rw */;')

    expect(result.source_files).to include(staged_irf_register_file)

    os2wb_source = File.read(os2wb_file)
    expect(os2wb_source).to include('`define TEST_DRAM        0')
    expect(os2wb_source).to include("`define MEM_SIZE         #{described_class::FAST_BOOT_MEM_SIZE}")
    expect(os2wb_source.scan(/^reg fifo_rd;$/).size).to eq(1)
    expect(os2wb_source.scan(/^wire \[123:0\] pcx_packet;$/).size).to eq(1)
    expect(os2wb_source).to include('wire        fast_boot_prom_ifill;')
    expect(os2wb_source).to include("assign fast_boot_prom_ifill = (pcx_packet_d[122:118]==5'b10000) && !pcx_req_d[4] &&")
    expect(os2wb_source).to include('if((pcx_packet_d[122:118]==5\'b10000) && !pcx_req_d[4] && !fast_boot_prom_ifill)')
    expect(os2wb_source).to include('if(pcx_req_d[4] || fast_boot_prom_ifill) // I/O access')
    expect(os2wb_source).to include("wb_addr<={pcx_req_d,19'b0,pcx_packet_d[103:64+3],3'b000};")
    expect(os2wb_source).to include('cpx_packet_1[136]<=fast_boot_prom_ifill ? 1\'b1 :')
    expect(os2wb_source).to include("if((pcx_packet_d[122:118]==5'b10000) && !fast_boot_prom_ifill) // IFill")
    expect(os2wb_source).to include("else if((pcx_packet_d[122:118]==5'b00000 && !pcx_packet_d[117] && !pcx_packet_d[110])) // Cacheble Load")
    expect(os2wb_source).to include("cpx_packet_1[133:131]<={1'b1,pcx_packet_d[108:107]};")
    expect(os2wb_source).to include("cpx_packet_2[133:131]<={1'b1,pcx_packet_d[108:107]};")
    expect(os2wb_source).to include('cpx_packet_1[130]<=((pcx_packet_d[122:118]==5\'b10000) && (pcx_req_d[4] || fast_boot_prom_ifill)) ? 1:0;')
    expect(os2wb_source).to include('if(pcx_req_d[4] || fast_boot_prom_ifill) // I/O access')
    expect(os2wb_source).to include('cpx_packet_1[127:0]<={wb_data_i[63:32],wb_data_i[63:32],wb_data_i[63:32],wb_data_i[63:32]};')
    expect(os2wb_source).to include("cpx_packet<=145'h1700000000000000000000000000000010001;")
    expect(os2wb_source).to include('cpx_ready<=1;')

    os2wb_dual_source = File.read(os2wb_dual_file)
    expect(os2wb_dual_source).to include('`define TEST_DRAM        0')
    expect(os2wb_dual_source).to include("`define MEM_SIZE         #{described_class::FAST_BOOT_MEM_SIZE}")
    expect(os2wb_dual_source.scan(/^reg fifo_rd;$/).size).to eq(1)
    expect(os2wb_dual_source.scan(/^reg fifo_rd1;$/).size).to eq(1)
    expect(os2wb_dual_source.scan(/^reg cpu;$/).size).to eq(1)
    expect(os2wb_dual_source.scan(/^reg cpu2;$/).size).to eq(1)
    expect(os2wb_dual_source.scan(/^wire \[123:0\] pcx_packet;$/).size).to eq(1)
    expect(os2wb_dual_source).to include('wire        fast_boot_prom_ifill;')
    expect(os2wb_dual_source).to include("assign fast_boot_prom_ifill = (pcx_packet_d[122:118]==5'b10000) && !pcx_req_d[4] &&")
    expect(os2wb_dual_source).to include('if((pcx_packet_d[122:118]==5\'b10000) && !pcx_req_d[4] && !fast_boot_prom_ifill)')
    expect(os2wb_dual_source).to include('if(pcx_req_d[4] || fast_boot_prom_ifill) // I/O access')
    expect(os2wb_dual_source).to include("wb_addr<={pcx_req_d,19'b0,pcx_packet_d[103:64+3],3'b000};")
    expect(os2wb_dual_source).to include('cpx_packet_1[136]<=fast_boot_prom_ifill ? 1\'b1 :')
    expect(os2wb_dual_source).to include("if((pcx_packet_d[122:118]==5'b10000) && !fast_boot_prom_ifill) // IFill")
    expect(os2wb_dual_source).to include("else if((pcx_packet_d[122:118]==5'b00000 && !pcx_packet_d[117] && !pcx_packet_d[110])) // Cacheble Load")
    expect(os2wb_dual_source).to include("cpx_packet_1[133:131]<={1'b1,pcx_packet_d[108:107]};")
    expect(os2wb_dual_source).to include("cpx_packet_2[133:131]<={1'b1,pcx_packet_d[108:107]};")
    expect(os2wb_dual_source).to include('cpx_packet_1[130]<=((pcx_packet_d[122:118]==5\'b10000) && (pcx_req_d[4] || fast_boot_prom_ifill)) ? 1:0;')
    expect(os2wb_dual_source).to include('if(pcx_req_d[4] || fast_boot_prom_ifill) // I/O access')
    expect(os2wb_dual_source).to include('cpx_packet_1[127:0]<={wb_data_i[63:32],wb_data_i[63:32],wb_data_i[63:32],wb_data_i[63:32]};')
    expect(os2wb_dual_source).not_to include("cpx_packet<=145'h1700000000000000000000000000000010001;")
    expect(os2wb_dual_source).to include('cpx_packet<=145\'b0;')
    expect(os2wb_dual_source).to include('cpx_ready<=0;')

	    staged_irf_register_source = File.read(staged_irf_register_file)
	    expect(staged_irf_register_source).to include('reg	[71:0]	reg_th0 /* verilator public_flat_rw */;')
	    expect(staged_irf_register_source).to include('reg	[71:0]	reg_th3 /* verilator public_flat_rw */;')

	    ifu_source = File.read(ifu_file)
	    expect(ifu_source).to include('wire [39:10]   itlb_ifq_paddr_raw_s;')
	    expect(ifu_source).to include('wire           fast_boot_prom_ifetch_bf;')
	    expect(ifu_source).to include('wire           fast_boot_prom_ifetch_window_bf;')
	    expect(ifu_source).to include('wire           fast_boot_dram_ifetch_bf;')
	    expect(ifu_source).to include('wire           fast_boot_ifq_icache_en_s_l;')
	    expect(ifu_source).to include("localparam [47:2] FAST_BOOT_PROM_PC_LO = 46'h0000_0000_2000;")
	    expect(ifu_source).to include("localparam [47:2] FAST_BOOT_PROM_PC_HI = 46'h0000_0000_2010;")
	    expect(ifu_source).to include('itlb_ifq_paddr_raw_s[`IC_TAG_HI:10]')
	    expect(ifu_source).to include('.fcl_ifq_icache_en_s_l(fast_boot_ifq_icache_en_s_l),')
	    expect(ifu_source).to include('assign fast_boot_prom_ifetch_window_bf = (fdp_icd_vaddr_bf[47:2] >= FAST_BOOT_PROM_PC_LO) &&')
	    expect(ifu_source).to include('assign fast_boot_prom_ifetch_bf = fast_boot_prom_ifetch_window_bf;')
	    expect(ifu_source).to include('assign fast_boot_dram_ifetch_bf = ~fast_boot_prom_ifetch_bf &&')
	    expect(ifu_source).to include('(fdp_icd_vaddr_bf[47:18] == 30\'b0);')
	    expect(ifu_source).to include('assign fast_boot_ifq_icache_en_s_l = fast_boot_dram_ifetch_bf ?')
	    expect(ifu_source).to include("                                        1'b0 :")
	    expect(ifu_source).to include('assign itlb_ifq_paddr_s[39:10] = fast_boot_prom_ifetch_bf ?')
	    expect(ifu_source).to include('fdp_icd_vaddr_bf[39:10] :')
	    expect(ifu_source).to include('itlb_ifq_paddr_raw_s[39:10]);')

	    ifu_fdp_source = File.read(ifu_fdp_file)
	    expect(ifu_fdp_source).to include('pc_bf_raw')
	    expect(ifu_fdp_source).to include('wire          fast_boot_pc_window;')
	    expect(ifu_fdp_source).to include("assign fast_boot_pc_window = 1'b0;")
	    expect(ifu_fdp_source).to include('assign fdp_icd_vaddr_bf = pc_bf[47:2];')
	    expect(ifu_fdp_source).to include('dp_mux3ds #(48) pcbf_mux(.dout  (pc_bf_raw[47:0]),')
	    expect(ifu_fdp_source).to include('assign pc_bf[47:0] = (pc_f[47:0] == 48\'b0) ?')
	    expect(ifu_fdp_source).to include("48'h0000_0000_8000")
	    expect(ifu_fdp_source).to include('nextpc_nosw_raw_bf')
	    expect(ifu_fdp_source).to include('dp_mux3ds #(49) pcp4_mux(.dout  (nextpc_nosw_raw_bf),')
	    expect(ifu_fdp_source).to include("49'h0_0000_0000_8004")

	    ifu_swl_source = File.read(ifu_swl_file)
	    expect(ifu_swl_source).to include('wire          start_on_rst;')
    expect(ifu_swl_source).to include('dffr_s #(10) thrrdy_ctr')
	    expect(ifu_swl_source).to include('assign proc0 = (const_cpuid == 4\'b0000) ? 1\'b1 : 1\'b0;')
	    expect(ifu_swl_source).to include('assign start_thread = {3\'b0, start_on_rst} |')
    expect(ifu_swl_source).to include('assign count_nxt[9:0] = (count[9:0] == 10\'d1023) ? 10\'d1023 :')
    expect(ifu_swl_source).to include('assign start_on_rst = (count[9:0] == 10\'d320) & proc0;')
	    expect(ifu_swl_source).to include('.completion(completion[0] | start_on_rst),')
	    expect(ifu_swl_source).to include('.schedule	(schedule[0] | start_on_rst),')
	    expect(ifu_swl_source).to include('.switch_out(switch_out & ~start_on_rst),')
	    expect(ifu_swl_source).to include('.stall     (all_stall[0] & ~start_on_rst),')

	    exu_rml_source = File.read(exu_rml_file)
	    expect(exu_rml_source.scan("assign new_agp[1:0] = reset ? 2'b00 : rml_irf_new_agp[1:0];").length).to eq(2)

	    lsu_source = File.read(lsu_file)
	    expect(lsu_source).to include('.ifu_lsu_pcxpkt_e_b49   (ifu_lsu_pcxpkt_e[49]),')
	    expect(lsu_source).to include('.ifu_lsu_pcxpkt_e_b49 (ifu_lsu_pcxpkt_e[49]),  // Templated')
	    expect(lsu_source).to include('wire                    fast_boot_dtlb_bypass_e;')
	    expect(lsu_source).to include('wire                    fast_boot_lsu_dtlb_bypass_e;')
	    expect(lsu_source).to include('assign fast_boot_dtlb_bypass_e =')
	    expect(lsu_source).to include('~ifu_lsu_alt_space_d &')
	    expect(lsu_source).to include('(exu_lsu_ldst_va_e[47:18] == 30\'b0);')
	    expect(lsu_source).to include('assign fast_boot_lsu_dtlb_bypass_e = lsu_dtlb_bypass_e | fast_boot_dtlb_bypass_e;')
	    expect(lsu_source).to include('.lsu_dtlb_bypass_e     (fast_boot_lsu_dtlb_bypass_e),')
	    expect(lsu_source).to include('.tlb_bypass            (fast_boot_lsu_dtlb_bypass_e),')
	    expect(lsu_source).to include('.tlb_bypass             (fast_boot_lsu_dtlb_bypass_e),     // Templated')

	    lsu_qctl1_source = File.read(lsu_qctl1_file)
	    expect(lsu_qctl1_source).to include('ifu_lsu_pcxpkt_e_b49')
	    expect(lsu_qctl1_source).to include('assign	lsu_ifu_pcxpkt_ack_d = imiss_pcx_rq_sel_d2 & ~pcx_req_squash_d1 ;')
	    expect(lsu_qctl1_source).to include('Keep real LSU acceptance timing for fast boot')

	    lsu_qctl2_source = File.read(lsu_qctl2_file)
	    expect(lsu_qctl2_source).to include('Only IFILL DFQ entries should retire the ibuf-forward mask.')
	    expect(lsu_qctl2_source).to include('dfq_rptr_vld_d1 & dfq_ifill_type & ~ifu_lsu_ibuf_busy & ~ifill_dinv_head_of_dfq_pend')

	    lsu_qctl2_source = File.read(lsu_qctl2_file)
	    expect(lsu_qctl2_source).to include('wire  [9:0]   fast_boot_count;')
	    expect(lsu_qctl2_source).to include('dffr_s #(10) fast_boot_ctr')
	    expect(lsu_qctl2_source).to include('assign fast_boot_count_nxt[9:0] = (fast_boot_count[9:0] == 10\'d1023) ? 10\'d1023 :')
	    expect(lsu_qctl2_source).to include('assign fast_boot_stall_bypass = fast_boot_proc0 & (fast_boot_count[9:0] < 10\'d320);')
	    expect(lsu_qctl2_source).to include('Only IFILL DFQ entries should retire the ibuf-forward mask.')
	    expect(lsu_qctl2_source).to include('dfq_rptr_vld_d1 & dfq_ifill_type & ~ifu_lsu_ibuf_busy & ~ifill_dinv_head_of_dfq_pend')
	    expect(lsu_qctl2_source).to include('fast_boot_stall_bypass ? 1\'b0 :')

	    sparc_rtl_source = File.read(sparc_rtl_file)
    expect(sparc_rtl_source).to include('wire                 fast_boot_reset_vector;')
    expect(sparc_rtl_source).to include('wire [1:0]           fast_boot_tlu_exu_agp;')
    expect(sparc_rtl_source).to include('wire [1:0]           fast_boot_tlu_exu_agp_tid;')
    expect(sparc_rtl_source).to include('wire                 fast_boot_agp_tid_window;')
    expect(sparc_rtl_source).to include("localparam [48:0]    FAST_BOOT_TRAPPC_W2  = 49'h0_0000_0000_8000;")
    expect(sparc_rtl_source).to include("localparam [48:0]    FAST_BOOT_TRAPNPC_W2 = 49'h0_0000_0000_8004;")
    expect(sparc_rtl_source).to include('assign fast_boot_agp_tid_window = 1\'b1;')
    expect(sparc_rtl_source).to include('assign fast_boot_tlu_exu_agp[1:0] = fast_boot_agp_tid_window ? 2\'b00 : tlu_exu_agp[1:0];')
    expect(sparc_rtl_source).to include('assign fast_boot_tlu_exu_agp_tid[1:0] = fast_boot_agp_tid_window ? 2\'b00 : tlu_exu_agp_tid[1:0];')
	    expect(sparc_rtl_source).to include('.tlu_ifu_trapnpc_w2    (fast_boot_tlu_ifu_trapnpc_w2[48:0]),')
	    expect(sparc_rtl_source).to include('.tlu_ifu_trappc_w2     (fast_boot_tlu_ifu_trappc_w2[48:0]),')
	    expect(sparc_rtl_source).to include('.tlu_exu_agp           (fast_boot_tlu_exu_agp[1:0]),')
	    expect(sparc_rtl_source).to include('.tlu_exu_agp_tid       (fast_boot_tlu_exu_agp_tid[1:0]),')

    tlu_tcl_source = File.read(tlu_tcl_file)
    expect(tlu_tcl_source).to include('wire fast_boot_agp_tid_force;')
    expect(tlu_tcl_source).to include('assign agp_tid_sel =')
    expect(tlu_tcl_source).to include("assign fast_boot_agp_tid_force = 1'b1;")
    expect(tlu_tcl_source).to include('(dnrtry_inst_g) | (tlu_gl_rw_g & wsr_inst_g);')

    support_stubs_source = File.read(support_stubs_file)
    expect(support_stubs_source).to include('module pcx_fifo(aclr, clock, data, rdreq, wrreq, empty, q);')
    expect(support_stubs_source).to include('output empty;')
    expect(support_stubs_source).to include('output [129:0] q;')
    expect(support_stubs_source).to include('reg [129:0] mem[0:3];')
    expect(support_stubs_source).not_to include('module bw_r_irf_register(')
  end

  it 'reuses the cached staged bundle for identical inputs', timeout: 120 do
    first = described_class.new(cache_root: cache_root, fast_boot: true).build
    second = described_class.new(cache_root: cache_root, fast_boot: true).build

    expect(second.build_dir).to eq(first.build_dir)
    expect(second.top_file).to eq(first.top_file)
    expect(second.source_files).to eq(first.source_files)
  end
end
